#z extraction for image reduction
INPUT_TIFF: /stat3d/morphologyTMA.ome.tif
Z_SLICE_A: 4
Z_SLICE_B: 5
LEVEL: 2

# QuPath parameters
CELL_EXPANSION: 2.0
SIGMA: 1.0
THRESHOLD: 30.0
MIN_AREA: 10.0
MAX_AREA: 1000.0
BACKGROUND_RADIUS: 10.0
MEDIAN_RADIUS: 0.0

#Image measurements script
sample_size: 15000

#Cellpose
directory: /stat3d
cellpose_img_filter: z4_and_z5_level2_morphology
cellpose_use_gpu: true

#Cell-to-transcript files and parameters
seg_data: /stat3d/z4_and_z5_level2_morphology_seg.npy
transcripts_df: /stat3d/transcriptsTMA.parquet
PIXEL_SIZE: 0.85
Z_SLICE_MICRON: 3


#NUC_EXP_PIXEL:average nuclear expansion / pixel size
#NUC_EXP_SLICE: average nuclear expansion / z slice micron 
