#STAT3D configuration file

# Set outputs directory
directory: /stat3d

#z extraction for image reduction
INPUT_TIFF: /stat3d/morphology_TC070.ome.tif
#Z_SLICE_A: 4
#Z_SLICE_B: 5
LEVEL: 2

# QuPath parameters
CELL_EXPANSION: 2.0
SIGMA: 1.0
THRESHOLD: 30.0
MIN_AREA: 10.0
MAX_AREA: 1000.0
BACKGROUND_RADIUS: 10.0
MEDIAN_RADIUS: 0.0

#Image measurements 
sample_size: 15000

#Cellpose
cellpose_use_gpu: true
cellpose_img_filter : morphology_TC070.ome_STAT3D

#Cell-to-transcript files and parameters
transcripts_df: /stat3d/transcriptsTC070.parquet

#Level 2 pixel size 
PIXEL_SIZE: 0.85

#Z slice spacing 
Z_SLICE_MICRON: 3

#NUC_EXP_PIXEL:(average nuclear expansion / pixel size)
#NUC_EXP_SLICE: (average nuclear expansion / z slice micron) 



